name       : linux-headers
version    : 4.9.68
release    : 32
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.68.tar.xz : db7f60637d8c455f91b34ddbdcb23916e6273bc6049b205c1bbc12608366c210
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
