name       : linux-headers
version    : 4.9.145
release    : 65
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.145.tar.xz : 6901ca37e8c305a2f26c598952338b4dc2481ca5a9d0bf71e2b71730a5b5bc5e
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
