name       : linux-headers
version    : 4.9.18
release    : 4
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.18.tar.xz : a10eea12a85667636ea2503aebcdae3005c821333c489fc54e2a4e9fc44261d1
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
