name       : linux-headers
version    : 4.8.17
release    : 2
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.8.17.tar.xz : eabae4a85799287e15b23f3812864913ef703a03bfb4aec2bce23fbc97c160fe
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
