name       : linux-headers
version    : 5.15.68
release    : 92
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.68.tar.xz : 17bbb3cb5c9ba18583b6679cc28f828aec49c72abbfc6fbde310b0cb17218b7e
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
