name       : linux-headers
version    : 4.9.84
release    : 46
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.84.tar.xz : 6cb86c89762ce8b75a51045d12d00a88040d0b6ab9dfbcafabfe8b127caf1bb7
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
