name       : linux-headers
version    : 5.15.30
release    : 90
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.30.tar.gz : 10b2ec2737d526ca8ae2a325505f1e785a4f5bdc423aa37dd2c41f7f0990dd73
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
