name       : linux-headers
version    : 5.13.0
release    : 71
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.13.tar.xz : 3f6baa97f37518439f51df2e4f3d65a822ca5ff016aa8e60d2cc53b95a6c89d9
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
