name       : linux-headers
version    : 4.9.72
release    : 35
source     :
    - https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.9.72.tar.xz : 69f201f1eb9eade9a3cde26d3896a53df9fddf1e19f9fa7b36331b8b1976b83b
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
