name       : linux-headers
version    : 4.9.22
release    : 5
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.22.tar.xz : dbdb1c58706a9010627f1fb68f3246f37544f2b6e2df524925c181e249b8036a
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
