name       : linux-headers
version    : 5.14.14
release    : 84
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.14.14.tar.xz : 4dff4e96d4052195002538027f8a810411ba6116a41bff5575952702d509d06a
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
