name       : linux-headers
version    : 4.9.36
release    : 8
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.36.tar.xz : a001e96a042839d813b659d7af920db6defce9a1a2140051c6ee04ea0a2ec1f4
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
