name       : linux-headers
version    : 5.14.4
release    : 80
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.14.4.tar.xz : 42e279e0d022ed702bc59b4548b60d1bd526b32caf6bc146421d53a9f17132b6
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
