name       : linux-headers
version    : 6.0.9
release    : 93
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.0.9.tar.xz : 6114a208e82739b4a1ab059ace35262be2a83be34cd1ae23cb8a09337db831c7
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
