name       : linux-headers
version    : 4.9.101
release    : 55
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.101.tar.xz : af95d02b07e900ec4a49670aa2c9d95bf3238748c908cf506ce77aeaa5e7aa00
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
