name       : linux-headers
version    : 5.6.4
release    : 69
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.6.4.tar.xz : 5df1741e550cb6fa7471530f42da98bac5093e693e2c4f3aef4393d8135b9d91
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
