name       : linux-headers
version    : 4.9.93
release    : 51
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.93.tar.xz : 58f78ab6c945c64a7c7c246256dc8b516b009c9ef1c90572ae396e7a8d6a5903
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
