name       : linux-headers
version    : 5.15.61
release    : 91
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.61.tar.gz : 52cee3df0226004cb6d963a61271c76b503bbac97057ca7c3f9c95947c4ea1fe
license    : GPL-2.0-only
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
