name       : linux-headers
version    : 4.9.46
release    : 14
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.46.tar.xz : 228393e9f0e388112adb55398289ebb9334cd22586810c0333ede08b68aa2b2b
license    :
    - GPL-2.0
component  : system.devel
replaces   : kernel-libc-devel
summary    : Kernel's libc headers
patterns   :
    - /*
description: |
    Headers for the kernel's libc implementation
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
